kafka:
    name: "agent_kafka"
    bootstrap_servers: "[CONFLUENT CLOUD URL]:9092"
    group_id: "agent_group_abc"
    client_id: "agent_client_abc"
    sasl_plain_username: "[SASL USERNAME]"
    sasl_plain_password: "[SASL PASSWORD]"
    security_protocol: "SASL_SSL"
    sasl_mechanism: "PLAIN"
    schema_registry:
        url: "[SCHEMA REGISTRY URL]"
        api_key: "[SCHEMA REGISTRY API KEY]"
        api_secret: "[SCHEMA REGISTRY API SECRET]"
agent:
    request_topic: "agent_request_topic"
    response_topic: "agent_response_topic"