[tool.uv.workspace]
members = ["packages/autogen-kafka/src"]
# members = ["packages/autogen_kafka","packages/exemple"]

[tool.hatch.build.targets.wheel]
packages = ["packages/autogen_kafka"]

[tool.uv.sources]
autogen_kafka = { workspace = true }
exemple = { workspace = true }

[tool.hatch.metadata]
allow-direct-references = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "autogen-kafka"
version = "0.1.4"
description = "autogen kafka support extension"
keywords = ["autogen", "kafka", "extension"]
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
    "autogen>=0.6.1",
    "autogen-core>=0.6.1",
    "kstreams>=0.26.9",
    "confluent-kafka>=2.10.1",
    "confluent-kafka[json]>=2.10.1",
    "azure-core>=1.34.0",
    "autogen-ext[grpc]>=0.6.1",
    "aiorun>=2017.10.2",
    "grpcio>=1.70.0",
    "aiorun>=2025.1.1",
    "hatchling>=1.27.0",
    "kstreams>=0.26.9",
    "pyautogen>=0.9",
]
authors = [
  { name="Confluent Inc", email="info@confluent.io" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://confluent.io"

[project.optional-dependencies]
yaml = ["pyyaml>=6.0"]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
    "pytest-asyncio>=1.0.0",
    "testcontainers>=4.10.0",
    "autogen-ext>=0.6.1",
]
