[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["autogen-kafka-extension-sample/src/"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv.sources]
autogen-kafka-extension = { workspace = true }

[project]
name = "autogen-kafka-extension-sample"
version = "0.1.0"
description = "autogen kafka sample application extension"
keywords = ["autogen", "kafka", "extension"]
requires-python = ">=3.10"
dependencies = [
    "autogen>=0.6.1",
    "autogen-core>=0.6.1",
    "kstreams>=0.26.9",
    "confluent-kafka>=2.10.1",
    "confluent-kafka[json]>=2.10.1",
    "azure-core>=1.34.0",
    "autogen-ext[grpc]>=0.6.1",
    "aiorun>=2017.10.2",
    "grpcio>=1.70.0",
    "autogen-kafka",
    "autogen-agentchat>=0.6.1",
    "openai>=1.97.0",
]

[project.optional-dependencies]
yaml = ["pyyaml>=6.0"]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
    "pytest-asyncio>=1.0.0",
    "testcontainers>=4.10.0",
    "autogen-ext>=0.6.1",
]
